//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quinelita.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quinelita.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE Equipos
        ///DELETE Ligas.
        /// </summary>
        internal static string SeedData_Down {
            get {
                return ResourceManager.GetString("SeedData_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT Usuarios ON; 
        ///INSERT INTO Usuarios (Id,Email)
        ///VALUES (1,&apos;Usuario1@email.com&apos;)
        ///INSERT INTO Usuarios (Id,Email)
        ///VALUES (2,&apos;Usuario2@email.com&apos;)
        ///INSERT INTO Usuarios (Id,Email)
        ///VALUES (3,&apos;Usuario3@email.com&apos;)
        ///INSERT INTO Usuarios (Id,Email)
        ///VALUES (4,&apos;Usuario4@email.com&apos;)
        ///INSERT INTO Usuarios (Id,Email)
        ///VALUES (5,&apos;Usuario5@email.com&apos;)
        ///INSERT INTO Usuarios (Id,Email)
        ///VALUES (6,&apos;Usuario6@email.com&apos;)
        ///SET IDENTITY_INSERT Usuarios OFF; 
        ///
        ///INSERT INTO Ligas (Id,Nombre)
        ///VALUES (1,&apos;M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeedData_Up {
            get {
                return ResourceManager.GetString("SeedData_Up", resourceCulture);
            }
        }
    }
}
